export const GET_USER_INFO = "GET_USER_INFO";
export const GET_EMP_MASTER = "GET_EMP_MASTER";
export const GET_PRESENCE_MASTER = "GET_PRESENCE_MASTER";
export const GET_LOGIN_DETAILS = "GET_LOGIN_DETAILS";
export const GET_BREAK_DETAILS = "GET_BREAK_DETAILS";



export const GET_LOGIN_DETAILS_USER = "GET_LOGIN_DETAILS_USER";